name: 'Release'
description: 'Releases a package'
inputs:
  scope:
    description: 'The package to release. Must match a package specified in lerna.json.'
  version:
    description: 'The type of version to release.'
  tag:
    description: 'The tag to publish to on NPM.'
  preid:
    description: 'The prerelease identifier used when doing a prerelease.'
  working-directory:
    description: 'The directory of the package.'
  folder:
    default: './'
    description: 'A folder containing a package.json file.'
  token:
    description: 'The NPM authentication token required to publish.'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    # Provenance requires npm 9.5.0+
    - name: Install latest npm
      run: npm install -g npm@latest
      shell: bash
    # This ensures the local version of Lerna is installed
    # and that we do not use the global Lerna version
    - name: Install root dependencies
      run: pnpm install
      shell: bash
    - name: Install project dependencies
      run: pnpm install
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Update Version
      run: pnpm exec lerna@5 version ${{ inputs.version }} --yes --exact --no-changelog --no-push --no-git-tag-version --preid=${{ inputs.preid }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Run Build
      run: pnpm run build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Prepare NPM Token
      run: pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.token }}
    - name: Publish to NPM
      run: pnpm publish ${{ inputs.folder }} --tag ${{ inputs.tag }} --provenance --no-git-checks
      shell: bash
      working-directory: ${{ inputs.working-directory }}
