name: 'Test Angular E2E'
description: 'Test Angular E2E'
inputs:
  app:
    description: 'The specific test application'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-core
        path: ./packages/core
        filename: CoreBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-angular
        path: ./angular
        filename: AngularBuild.zip
    - uses: ./.github/workflows/actions/download-archive
      with:
        name: ionic-angular-server
        path: ./packages/angular-server
        filename: AngularServerBuild.zip
    - name: Create Test App
      run: ./build.sh ${{ inputs.app }}
      shell: bash
      working-directory: ./test-apps/angular
    - name: Install Dependencies
      run: pnpm install
      shell: bash
      working-directory: ./test-apps/angular/build/${{ inputs.app }}
    - name: Run Tests
      run: pnpm run test
      shell: bash
      working-directory: ./test-apps/angular/build/${{ inputs.app }}
